### ISSUE TITLE
fika compatible

### ISSUE THREAD

**Issue by M0T0FAM93** [CJ-SPT/Skills-Extended#21]
would love if this was make fika compatible as this is the error i am getting when using fika, not sure if it is fika related or not but that would be my guess as its the only mod installed

NOTE: this is fresh server and profile being created

TypeError: Cannot read properties of undefined (reading 'Nickname')
TypeError: Cannot read properties of undefined (reading 'Nickname')
    at ProgressionManager.checkForOrCreateProgressFile (C:\SPT2\user\mods\SkillsExtended\src\Managers\ProgressionManager.ts:81:97)
    at ProgressionManager.getActivePmcData (C:\SPT2\user\mods\SkillsExtended\src\Managers\ProgressionManager.ts:44:14)
    at Object.action (C:\SPT2\user\mods\SkillsExtended\src\Managers\RouteManager.ts:47:49)
    at StaticRouterMod.handleStatic (C:\snapshot\src\di\Router.ts:41:63)
    at HttpRouter.handleRoute (C:\snapshot\src\routers\HttpRouter.ts:61:68)
    at HttpRouter.getResponse (C:\snapshot\src\routers\HttpRouter.ts:34:36)
    at HttpRouter.getResponse (C:\SPT2\user\mods\fika-server\src\overrides\routers\HttpRouter.ts:25:63)
    at SptHttpListener.getResponse (C:\snapshot\src\servers\http\SptHttpListener.ts:130:44)
    at SptHttpListener.handle (C:\snapshot\src\servers\http\SptHttpListener.ts:31:45)
    at HttpServer.handleRequest (C:\snapshot\src\servers\HttpServer.ts:96:32)
TypeError: Cannot read properties of undefined (reading 'Nickname')
TypeError: Cannot read properties of undefined (reading 'Nickname')
    at ProgressionManager.checkForOrCreateProgressFile (C:\SPT2\user\mods\SkillsExtended\src\Managers\ProgressionManager.ts:81:97)
    at ProgressionManager.getActivePmcData (C:\SPT2\user\mods\SkillsExtended\src\Managers\ProgressionManager.ts:44:14)
    at Object.action (C:\SPT2\user\mods\SkillsExtended\src\Managers\RouteManager.ts:47:49)
    at StaticRouterMod.handleStatic (C:\snapshot\src\di\Router.ts:41:63)
    at HttpRouter.handleRoute (C:\snapshot\src\routers\HttpRouter.ts:61:68)
    at HttpRouter.getResponse (C:\snapshot\src\routers\HttpRouter.ts:34:36)
    at HttpRouter.getResponse (C:\SPT2\user\mods\fika-server\src\overrides\routers\HttpRouter.ts:25:63)
    at SptHttpListener.getResponse (C:\snapshot\src\servers\http\SptHttpListener.ts:130:44)
    at SptHttpListener.handle (C:\snapshot\src\servers\http\SptHttpListener.ts:31:45)
    at HttpServer.handleRequest (C:\snapshot\src\servers\HttpServer.ts:96:32)

**Comment by CJ-SPT** [comment]
Not a Fika issue, that's also an experimental test release of 1.2.0 you're using. Fixed with 4ff864f
