### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by WongHoDaddy** [CJ-SPT/Skills-Extended#37]
I’m trying to install the “skill extended” mod. It looked really interesting, especially the whole lock picking aspect. But the newest version of 1.4.0 just doesn’t work, I install everything and it says it’s missing files. 
User/mods/skills extended/data/images/achievements
Does anyone have a similar issue?

**Comment by WongHoDaddy** [comment]
Error: ENOENT: no such file or directory, scandir 'C:\SPT\user\mods\SkillsExtended\data\Images\Achievements'
Error: ENOENT: no such file or directory, scandir 'C:\SPT\user\mods\SkillsExtended\data\Images\Achievements'
    at Object.readdirSync (node:fs:1515:26)
    at Object.readdirSync (pkg/prelude/bootstrap.js:1306:35)
    at IOManager.importAllImages (C:\SPT\user\mods\SkillsExtended\src\Managers\IOManager.ts:172:30)
    at IOManager.importData (C:\SPT\user\mods\SkillsExtended\src\Managers\IOManager.ts:45:14)
    at SkillsExtended.postDBLoad (C:\SPT\user\mods\SkillsExtended\src\mod.ts:63:24)
    at PostDBModLoader.executeModsAsync (C:\snapshot\src\loaders\PostDBModLoader.ts:63:45)
    at PostDBModLoader.onLoad (C:\snapshot\src\loaders\PostDBModLoader.ts:26:13)
    at App.load (C:\snapshot\src\utils\App.ts:53:13)
Error: ENOENT: no such file or directory, scandir 'C:\SPT\user\mods\SkillsExtended\data\Images\Achievements'
Error: ENOENT: no such file or directory, scandir 'C:\SPT\user\mods\SkillsExtended\data\Images\Achievements'
    at Object.readdirSync (node:fs:1515:26)
    at Object.readdirSync (pkg/prelude/bootstrap.js:1306:35)
    at IOManager.importAllImages (C:\SPT\user\mods\SkillsExtended\src\Managers\IOManager.ts:172:30)
    at IOManager.importData (C:\SPT\user\mods\SkillsExtended\src\Managers\IOManager.ts:45:14)
    at SkillsExtended.postDBLoad (C:\SPT\user\mods\SkillsExtended\src\mod.ts:63:24)
    at PostDBModLoader.executeModsAsync (C:\snapshot\src\loaders\PostDBModLoader.ts:63:45)
    at PostDBModLoader.onLoad (C:\snapshot\src\loaders\PostDBModLoader.ts:26:13)
    at App.load (C:\snapshot\src\utils\App.ts:53:13)

**Comment by zhua-w** [comment]
Windows server or Linux server?

**Comment by WongHoDaddy** [comment]
Windows

**Comment by CJ-SPT** [comment]
Not reproducible, likely user error. Closing
