### ISSUE TITLE
[1.4.0] Lockpicking: Doors not in database

### ISSUE THREAD

**Issue by Brin-47** [CJ-SPT/Skills-Extended#38]
I've found several "doors" across several maps--I'll split them up into multiple comments here for enhanced readability:

Shoreline: All 4 locked safes (Cottage safe, W321, Management Office, & Management Warehouse).
Cottage safe = Lootable_00004, key should be "5a0f068686f7745b0d4ea242"
321 safe = ...DesignStuff_00208, key should be "5a0eff2986f7741fd654e684"
Management office = ...DesignStuff_00211, key should be "5a0f08bc86f77478f33b84c2"
Management warehouse = ...DesignStuff_00212, key should be "5a0f0f5886f7741c4e32a472"

![2024-12-09 18-18 _-165 5, 3 4, -88 6_0 0, -0 9, 0 5, 0 0_22 18 (0)](https://github.com/user-attachments/assets/b4d6ff61-4cca-4d47-99be-91c92e8343bf)
![2024-12-09 18-38 _-266 8, 0 6, -147 1_-0 3, -0 7, 0 3, -0 6_0 51 (0)](https://github.com/user-attachments/assets/9e0eaa9f-e61b-498e-a675-7cdc54bf6f4b)
![2024-12-09 18-40 _-242 2, 0 5, -152 8_0 0, 0 9, -0 5, 0 0_0 69 (0)](https://github.com/user-attachments/assets/2ec495e1-0c56-4893-9759-e7688c9ee413)
![2024-12-09 18-08 _92 9, -44 7, 112 2_0 2, 0 7, -0 2, 0 7_21 03 (0)](https://github.com/user-attachments/assets/14c224fb-bfb7-4fdc-898b-33b85191e803)

**Comment by Brin-47** [comment]
On Lighthouse, Merin Car Trunk "61aa5b518f5e7a39b41416e2":

![2024-12-11 18-31 _91 3, 8 6, -130 2_0 0, -0 8, 0 5, 0 1_23 67 (0)](https://github.com/user-attachments/assets/99c8dc9b-11b7-4839-aa40-e96934372694)

**Comment by Brin-47** [comment]
On Interchange: Ultra Medical Storage, Kiba Outer, & Kiba Inner:

Ultra Med: ...DesignStuff_00050, key should be "5e42c71586f7747f245e1343"
Kiba Inner: ..."DesignStuff_00049, key should be "5addaffe86f77470b455f900"
Kiba Outer: ...DesignStuff_00052, key should be "5ad5d7d286f77450166e0a89"
![2024-12-17 02-53 _-10 3, 28 6, -34 5_0 0, -0 7, 0 0, -0 7_22 19 (0)](https://github.com/user-attachments/assets/3588f9f2-a8bf-4be4-8645-d9ce7f0a5a9a)
![2024-12-17 02-55 _68 1, 38 0, 40 5_-0 1, 0 8, -0 1, -0 6_22 47 (0)](https://github.com/user-attachments/assets/baae5860-66ec-450e-b94c-d07e0a3bff32)
![2024-12-17 02-53 _-8 8, 28 6, -33 6_0 0, -0 9, 0 1, 0 4_22 20 (0)](https://github.com/user-attachments/assets/e0d1c594-cf3b-46bb-ae63-4456a3d233b7)

**Comment by WongHoDaddy** [comment]
How did you even get the mod to load? The server says im missing files

Error: ENOENT: no such file or directory, scandir 'C:\SPT\user\mods\SkillsExtended\data\Images\Achievements'
Error: ENOENT: no such file or directory, scandir 'C:\SPT\user\mods\SkillsExtended\data\Images\Achievements'
    at Object.readdirSync (node:fs:1515:26)
    at Object.readdirSync (pkg/prelude/bootstrap.js:1306:35)
    at IOManager.importAllImages (C:\SPT\user\mods\SkillsExtended\src\Managers\IOManager.ts:172:30)
    at IOManager.importData (C:\SPT\user\mods\SkillsExtended\src\Managers\IOManager.ts:45:14)
    at SkillsExtended.postDBLoad (C:\SPT\user\mods\SkillsExtended\src\mod.ts:63:24)
    at PostDBModLoader.executeModsAsync (C:\snapshot\src\loaders\PostDBModLoader.ts:63:45)
    at PostDBModLoader.onLoad (C:\snapshot\src\loaders\PostDBModLoader.ts:26:13)
    at App.load (C:\snapshot\src\utils\App.ts:53:13)

**Comment by CJ-SPT** [comment]
Resolved with 2277526af3666a1a46c4c713b12bc3229e94353d will be included in 1.4.1
